import SEOMeta from '../components/SEOMeta'
import { SITE_NAME, CONTACT_EMAIL } from '../lib/brand'

// Draft page — built as a real, working mockup (more useful to review than a
// static image) rather than final legal copy. Deliberately NOT linked from
// the Navbar or Footer yet, and kept noindex, so nothing reaches a real
// visitor or search engine until you've reviewed it and had it checked
// against POPIA by someone qualified to do that. See docs/checklist.md for
// the placement recommendation once it's approved.
interface PolicySection {
  title: string
  paragraphs: string[]
}

const SECTIONS: PolicySection[] = [
  {
    title: 'Introduction',
    paragraphs: [
      `${SITE_NAME} ("we", "us", "our") respects your privacy. This policy explains what personal information we collect when you use this website, why we collect it, and what rights you have over it under South Africa's Protection of Personal Information Act (POPIA).`,
    ],
  },
  {
    title: 'Information We Collect',
    paragraphs: [
      "When you submit the contact form, we collect the information you provide directly — your name, email address, and the message you send us. We don't ask for anything beyond what's needed to reply to you.",
      "Like most websites, our hosting provider automatically logs standard technical information (such as IP address and browser type) for security and performance purposes. We don't currently run analytics or advertising cookies on this site.",
    ],
  },
  {
    title: 'How We Use Your Information',
    paragraphs: [
      "We use the information you submit solely to respond to your enquiry and, if you become a client, to deliver the services we agree on. We don't sell your information, and we don't share it with third parties for their own marketing purposes.",
    ],
  },
  {
    title: 'Third-Party Services',
    paragraphs: [
      'We use Resend to deliver the emails generated by our contact form, and Vercel to host this website. Both process the minimum data necessary to perform that function on our behalf and are bound by their own privacy and security commitments.',
    ],
  },
  {
    title: 'Cookies',
    paragraphs: [
      "This site does not currently use analytics, advertising, or tracking cookies. If that changes — for example, if we add website analytics in future — this policy will be updated first, and where required, you'll be asked for consent.",
    ],
  },
  {
    title: 'Data Security',
    paragraphs: [
      'We take reasonable technical and organisational measures to protect the information you share with us against loss, misuse, and unauthorised access.',
    ],
  },
  {
    title: 'Your Rights',
    paragraphs: [
      'Under POPIA, you have the right to ask what personal information we hold about you, to request it be corrected or deleted, and to object to how it is used. To exercise any of these rights, contact us using the details below.',
    ],
  },
  {
    title: 'Changes to This Policy',
    paragraphs: [
      'We may update this policy from time to time as our practices or the law change. The date of the most recent update will always be reflected at the top of this page once published.',
    ],
  },
  {
    title: 'Contact Us',
    paragraphs: [`Questions about this policy or your information? Email us at ${CONTACT_EMAIL}.`],
  },
]

export default function PrivacyPolicy() {
  return (
    <>
      <SEOMeta
        title="Privacy Policy"
        description="How Alioth Marketing Solutions collects, uses, and protects your personal information."
        path="/privacy"
        noindex
      />

      <section className="relative overflow-hidden px-6 py-24 text-center">
        <div
          aria-hidden="true"
          className="pointer-events-none absolute inset-x-0 top-0 -z-10 h-72 bg-gradient-to-b from-green/25 to-transparent blur-3xl md:h-96"
        />
        <div className="mx-auto max-w-3xl">
          <span className="inline-block rounded-full border border-green/30 bg-green/5 px-4 py-1.5 font-mono text-xs uppercase tracking-widest text-green">
            Draft — for internal review, not yet linked from the site
          </span>
          <h1 className="mt-6 font-display text-4xl font-black text-ink md:text-5xl">Privacy Policy</h1>
          <p className="mt-6 font-sans text-lg text-ink/70">
            How we collect, use, and protect your personal information on this website.
          </p>
        </div>
      </section>

      <div className="mx-auto max-w-3xl divide-y divide-ink/10 px-6 pb-24">
        {SECTIONS.map((section) => (
          <section key={section.title} className="py-8">
            <h2 className="font-serif text-2xl text-ink">{section.title}</h2>
            <div className="mt-4 space-y-4">
              {section.paragraphs.map((paragraph) => (
                <p key={paragraph.slice(0, 24)} className="font-sans text-lg text-ink/70">
                  {paragraph}
                </p>
              ))}
            </div>
          </section>
        ))}
      </div>
    </>
  )
}
